import { NextRequest, NextResponse } from "next/server";

import { fetchAndDeleteLoginCodeData } from "@/lib/emails/send-verification-request";
import { ratelimit } from "@/lib/redis";

// Rate limiters
const emailRateLimit = ratelimit(5, "1 m"); // 5 attempts per minute per email
const ipRateLimit = ratelimit(10, "1 m"); // 10 attempts per minute per IP

function getClientIp(request: NextRequest): string {
  const forwarded = request.headers.get("x-forwarded-for");
  const realIp = request.headers.get("x-real-ip");
  return forwarded?.split(",")[0]?.trim() || realIp || "unknown";
}

// Resolve the origin the request actually came in on. The stored callbackUrl
// is generated by NextAuth using NEXTAUTH_URL (which falls back to
// http://localhost:3000 when unset), so it can point at localhost even when
// the user is on a public preview/production origin. Navigating a public page
// to localhost triggers a browser "Private Network Access" block and the
// sign-in never completes. Rebuilding the URL on the real request origin makes
// the callback same-origin and lets the session cookie be set correctly.
function getRequestOrigin(request: NextRequest): string | null {
  const forwardedHost = request.headers.get("x-forwarded-host");
  const host = forwardedHost || request.headers.get("host");
  if (!host) return null;
  const proto =
    request.headers.get("x-forwarded-proto") ||
    (host.startsWith("localhost") || host.startsWith("127.0.0.1")
      ? "http"
      : "https");
  return `${proto}://${host}`;
}

// Rewrite the host/protocol of the NextAuth callback URL (and its inner
// redirect target) to the current request origin, preserving the token.
function rewriteCallbackToOrigin(
  callbackUrl: string,
  origin: string | null,
): string {
  if (!origin) return callbackUrl;
  try {
    const current = new URL(origin);
    const parsed = new URL(callbackUrl, origin);
    parsed.protocol = current.protocol;
    parsed.host = current.host;

    const inner = parsed.searchParams.get("callbackUrl");
    if (inner) {
      try {
        const innerUrl = new URL(inner, origin);
        if (
          innerUrl.hostname === "localhost" ||
          innerUrl.hostname === "127.0.0.1" ||
          innerUrl.host === current.host
        ) {
          innerUrl.protocol = current.protocol;
          innerUrl.host = current.host;
          parsed.searchParams.set("callbackUrl", innerUrl.toString());
        }
      } catch {
        // ignore malformed inner callbackUrl
      }
    }
    return parsed.toString();
  } catch {
    return callbackUrl;
  }
}

// POST: Verify via email + code
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { email, code } = body;

    // Type checks first to prevent calling .trim() on non-strings
    if (typeof email !== "string" || typeof code !== "string") {
      return NextResponse.json(
        { error: "Email and code are required." },
        { status: 400 },
      );
    }

    // Normalize after type check
    const normalizedEmail = email.trim().toLowerCase();
    const normalizedCode = code.trim().toUpperCase();

    // Validate non-empty email and exact code length
    if (!normalizedEmail || normalizedCode.length !== 10) {
      return NextResponse.json(
        { error: "Invalid email or code format." },
        { status: 400 },
      );
    }

    const ip = getClientIp(request);

    // Check both rate limits
    const [emailLimit, ipLimit] = await Promise.all([
      emailRateLimit.limit(`verify_code:${normalizedEmail}`),
      ipRateLimit.limit(`verify_code:ip:${ip}`),
    ]);

    if (!emailLimit.success) {
      return NextResponse.json(
        {
          error: "Too many attempts. Please wait before trying again.",
          retryAfter: Math.ceil((emailLimit.reset - Date.now()) / 1000),
          remaining: 0,
        },
        { status: 429 },
      );
    }

    if (!ipLimit.success) {
      return NextResponse.json(
        {
          error: "Too many attempts. Please wait before trying again.",
          retryAfter: Math.ceil((ipLimit.reset - Date.now()) / 1000),
          remaining: 0,
        },
        { status: 429 },
      );
    }

    // Atomically fetch and delete to prevent TOCTOU race condition
    const loginCodeData = await fetchAndDeleteLoginCodeData(
      normalizedEmail,
      normalizedCode,
    );

    if (!loginCodeData) {
      return NextResponse.json(
        {
          error: "Invalid code. Please check your email and try again.",
          remaining: emailLimit.remaining,
        },
        { status: 401 },
      );
    }

    const { callbackUrl } = loginCodeData;

    // Ensure the callback targets the origin the user is actually on, not the
    // localhost fallback baked in when NEXTAUTH_URL is unset.
    const origin = getRequestOrigin(request);
    const resolvedCallbackUrl = rewriteCallbackToOrigin(callbackUrl, origin);

    return NextResponse.json({ callbackUrl: resolvedCallbackUrl });
  } catch (error) {
    console.error("Error verifying code:", error);
    return NextResponse.json(
      { error: "Verification failed. Please try again." },
      { status: 500 },
    );
  }
}
